version: "3"

services:
        fastapi-ml-learning:
                build: .
                container_name: fastapi-ml-learning
                ports:
                        - 8000:8000

networks:
        default:
                driver: bridge
